# Generated by Django 5.0.3 on 2024-03-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper_app', '0005_alter_user_phone_code_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='job_company_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='job_location',
        ),
    ]
