# Generated by Django 5.0.3 on 2024-03-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper_app', '0006_rename_company_job_job_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
