# Generated by Django 5.0.3 on 2024-03-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('job_scraper_app', '0007_job_job_description_job_job_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('create_job', 'Can Create Job')]},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='user_avatar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='interests',
            new_name='user_interest',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_code',
            new_name='user_phone_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='user_phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_users', related_query_name='custom_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='AttemptedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempted', models.DateTimeField(auto_now_add=True)),
                ('attempted_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_scraper_app.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_scraper_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_jobs', models.ManyToManyField(through='job_scraper_app.AttemptedJobs', to='job_scraper_app.job')),
                ('portfolio_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_scraper_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='attemptedjobs',
            name='user_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_scraper_app.user_portfolio'),
        ),
        migrations.DeleteModel(
            name='CustomUserPermission',
        ),
    ]
