# Generated by Django 5.0.3 on 2024-03-15 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper_app', '0008_alter_user_options_rename_avatar_user_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptedjobs',
            name='attempted_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_scraper_app.job'),
        ),
        migrations.AlterField(
            model_name='attemptedjobs',
            name='user_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_scraper_app.user_portfolio'),
        ),
        migrations.AlterField(
            model_name='attemptedjobs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_scraper_app.user'),
        ),
    ]
