# Generated by Django 5.0.3 on 2024-03-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper_app', '0009_alter_attemptedjobs_attempted_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptedjobs',
            name='attempted_job_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('complete', 'Complete')], default='ongoing', max_length=10),
        ),
    ]
