# Generated by Django 5.0.3 on 2024-03-16 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper_app', '0010_attemptedjobs_attempted_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptedjobs',
            name='user_portfolio',
        ),
        migrations.AddField(
            model_name='attemptedjobs',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_scraper_app.portfolio'),
        ),
    ]
